apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: user-{{ .Values.user.version }},order-{{ .Values.order.version }}
    app.openshift.io/vcs-uri: https://github.com/drhelius/grpc-demo-account
    app.openshift.io/vcs-ref: {{ .Values.account.version }}
  labels:
    app: account
    version: {{ .Values.account.version }}
    app.kubernetes.io/name: account
    app.kubernetes.io/version: {{ .Values.account.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app.openshift.io/runtime: golang
    group: {{ .Values.appName }}
  name: account-{{ .Values.account.version }}
spec:
  replicas: {{ .Values.account.replicas }}
  selector:
    matchLabels:
      app: account
      version: {{ .Values.account.version }}
  template:
    metadata:
      labels:
        app: account
        version: {{ .Values.account.version }}
    spec:
      containers:
      - image: {{ .Values.account.image }}:{{ .Values.account.version }}
        imagePullPolicy: Always
        name: account
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}Mi
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
