apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  istio:
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        ior_enabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: true
    grafana:
      enabled: true
    kiali:
      enabled: true
    mixer:
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
    tracing:
      enabled: true
      jaeger:
        template: all-in-one