apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: httpbin
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: httpbin
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: httpbin