apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
    app: httpbin
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: httpbin
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS