apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: httpbin
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: httpbin
spec:
  hosts:
  - httpbin.org
  gateways:
  - mesh
  - httpbin
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
  - match:
    - gateways:
      - httpbin
      port: 443
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
      weight: 100