apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
    app.kubernetes.io/name: order
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: order
spec:
  ports:
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: order
