apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: product
    app.kubernetes.io/name: product
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: product
spec:
  gateways:
  - mesh
  hosts:
  - product
  http:
  - route:
    - destination:
        host: product
        subset: current-version
      weight: 100